In [1]:
import pandas as pd

In [5]:
dataset = pd.read_csv("titanic.csv")

In [7]:
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [9]:
dataset.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [11]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
dataset.isnull()


PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [15]:
del dataset["Name"]

In [17]:
del  dataset["PassengerId"]

In [19]:
del  dataset["Ticket"]

In [21]:
dataset


Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

Preprossesing

In [23]:
one_hoted_dataset = pd.get_dummies(dataset["Sex"],dtype=int)

In [25]:
one_hoted_dataset

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [27]:
new_dataset = pd.concat([one_hoted_dataset,dataset], axis=1)

In [29]:
new_dataset

female  male  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0         0     1         0       3    male  22.0      1      0   7.2500   
1         1     0         1       1  female  38.0      1      0  71.2833   
2         1     0         1       3  female  26.0      0      0   7.9250   
3         1     0         1       1  female  35.0      1      0  53.1000   
4         0     1         0       3    male  35.0      0      0   8.0500   
..      ...   ...       ...     ...     ...   ...    ...    ...      ...   
886       0     1         0       2    male  27.0      0      0  13.0000   
887       1     0         1       1  female  19.0      0      0  30.0000   
888       1     0         0       3  female   NaN      1      2  23.4500   
889       0     1         1       1    male  26.0      0      0  30.0000   
890       0     1         0       3    male  32.0      0      0   7.7500   

    Cabin Embarked  
0     NaN        S  
1     C85        C  
2     NaN        S  
3    C123        S  
4     NaN        S  
..    ...      ...  
886   NaN        S  
887   B42        S  
888   NaN        S  
889  C148        C  
890   NaN        Q  

[891 rows x 11 columns]

In [31]:
one_hoted_dataset = pd.get_dummies(dataset["Embarked"],dtype=int)

In [33]:
one_hoted_dataset

C  Q  S
0    0  0  1
1    1  0  0
2    0  0  1
3    0  0  1
4    0  0  1
..  .. .. ..
886  0  0  1
887  0  0  1
888  0  0  1
889  1  0  0
890  0  1  0

[891 rows x 3 columns]

In [35]:
new_dataset = pd.concat([one_hoted_dataset,new_dataset], axis=1)

In [37]:
new_dataset

C  Q  S  female  male  Survived  Pclass     Sex   Age  SibSp  Parch  \
0    0  0  1       0     1         0       3    male  22.0      1      0   
1    1  0  0       1     0         1       1  female  38.0      1      0   
2    0  0  1       1     0         1       3  female  26.0      0      0   
3    0  0  1       1     0         1       1  female  35.0      1      0   
4    0  0  1       0     1         0       3    male  35.0      0      0   
..  .. .. ..     ...   ...       ...     ...     ...   ...    ...    ...   
886  0  0  1       0     1         0       2    male  27.0      0      0   
887  0  0  1       1     0         1       1  female  19.0      0      0   
888  0  0  1       1     0         0       3  female   NaN      1      2   
889  1  0  0       0     1         1       1    male  26.0      0      0   
890  0  1  0       0     1         0       3    male  32.0      0      0   

        Fare Cabin Embarked  
0     7.2500   NaN        S  
1    71.2833   C85        C  
2     7.9250   NaN        S  
3    53.1000  C123        S  
4     8.0500   NaN        S  
..       ...   ...      ...  
886  13.0000   NaN        S  
887  30.0000   B42        S  
888  23.4500   NaN        S  
889  30.0000  C148        C  
890   7.7500   NaN        Q  

[891 rows x 14 columns]

In [39]:
del  new_dataset["Sex"]
del  new_dataset["Embarked"]
del  new_dataset["Cabin"]


In [41]:
new_dataset.isnull().sum()

C             0
Q             0
S             0
female        0
male          0
Survived      0
Pclass        0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64

In [43]:
age_mean = new_dataset["Age"].mean()
new_dataset["Age"].fillna(age_mean,inplace=True)

C:\Users\hosei\AppData\Local\Temp\ipykernel_24896\3010651187.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_dataset["Age"].fillna(age_mean,inplace=True)


In [45]:
new_dataset["Nsurvived"]=new_dataset["Survived"]

In [47]:
del new_dataset["Survived"]

In [49]:
features = new_dataset.iloc[:, :-1]
labels = new_dataset.iloc[:, -1]
from sklearn.model_selection import train_test_split
x_tr, x_ts, y_tr, y_ts = train_test_split(features,labels, test_size=0.2)

In [51]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler=StandardScaler()
x_tr=scaler.fit_transform(x_tr)
x_ts=scaler.transform(x_ts)


************ Modelling ****************

Disition Tree

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
tree = DecisionTreeClassifier()
tree.fit(x_tr,y_tr)
pred = tree.predict(x_ts)
print(accuracy_score(pred, y_ts))
print(confusion_matrix(pred, y_ts))

0.7932960893854749
[[82 22]
 [15 60]]


SVM

In [55]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_tr, y_tr)
y_pred = svm.predict(x_ts)
print(accuracy_score(y_pred, y_ts))
print(confusion_matrix(y_pred, y_ts))

0.8156424581005587
[[91 27]
 [ 6 55]]


Neural Network

In [57]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(9,8,5))
model.fit(x_tr, y_tr)
predict = model.predict(x_ts)
print(accuracy_score(y_ts,predict))
print(confusion_matrix(y_ts,predict))

0.8100558659217877
[[92  5]
 [29 53]]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


test for  NAA

In [59]:
import numpy as np
test=np.array([0,0,1,0,1,1,19,0,2,53]).reshape(1,10)
model.predict(test)

array([0], dtype=int64)

In [24]:
new_dataset


C  Q  S  female  male  Pclass        Age  SibSp  Parch     Fare  \
0    0  0  1       0     1       3  22.000000      1      0   7.2500   
1    1  0  0       1     0       1  38.000000      1      0  71.2833   
2    0  0  1       1     0       3  26.000000      0      0   7.9250   
3    0  0  1       1     0       1  35.000000      1      0  53.1000   
4    0  0  1       0     1       3  35.000000      0      0   8.0500   
..  .. .. ..     ...   ...     ...        ...    ...    ...      ...   
886  0  0  1       0     1       2  27.000000      0      0  13.0000   
887  0  0  1       1     0       1  19.000000      0      0  30.0000   
888  0  0  1       1     0       3  29.699118      1      2  23.4500   
889  1  0  0       0     1       1  26.000000      0      0  30.0000   
890  0  1  0       0     1       3  32.000000      0      0   7.7500   

     Nsurvived  
0            0  
1            1  
2            1  
3            1  
4            0  
..         ...  
886          0  
887          1  
888          0  
889          1  
890          0  

[891 rows x 11 columns]